# Site settings
title: SANE.digital
email: contact@sane.digital
url: http://sane.digital
description: "SANE.digital helps non-technical founders build their ideas and publish them on the App Store."
keywords: "mobile dev, mobile development, mobile developer, mobile app, mobile apps, ios development, ios developer, ios dev, ios apps, ios app, iphone development, iphone developer, iphone dev, iphone apps, iphone app, android app, android apps, android dev, android developer, android development, ios agency, ios studio, mobile studio, mobile agency, android agency, android studio, product studio, product development, product design, ios design, mobile design, android design"
skills: "We help non-technical founders build their ideas and publish them on the App Store."
meta_author: Knight James

# Google webmaster tools
# google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "000000" #80B3FF
  primary-rgb: "0,0,0" #"128,179,255"
  secondary: "202020"
  secondary-dark: "101010" #A2122F

# Footer settings
footer:
  copyright: SANE.digital
  location: Location
  social: Around the Web
  credits: Contact Us

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sanedigital
  - title: facebook
    url: 
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Carrer Serrano Morales, 5
  - line: 46004 Valencia, Spain

# Credits content
credits: 'Send us an email [here](mailto:james@sane.digtal)'

# Build settings
markdown: kramdown
permalink: pretty
